language: node_js

node_js:
    - 4.1

before_install:
    - gem install sass
    - npm install -g bower
    - npm install -g gulp

before_script:
    - npm install
    - bower install

script:
    - npm test
    - gulp frontsize:build
    - cd ./example_source
    - gulp frontsize:css
    - cd ../
    - node index.js --config a-pollo.travis.yml
    - node index.js --config a-pollo.test.travis.yml
